kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: nginx-daeman
  namespace: nginx
spec:
#  replicas: 3 in deamentset no replicaset
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-daeman-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
